### ISSUE TITLE
Login does not work anymore

### ISSUE THREAD

**Issue by Rayzen-dev** [t-abraham/instagent#12]
The login does not work anymore, I think it's due to somes changes by Instagram. Here is the trace:

```
Attempt to login...
Traceback (most recent call last):
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/friendships/7285760724/following/?rank_token=7285760724_e8d9e19c-7be7-40a9-88da-7eec7ac40a33&search_surface=follow_list_page&includes_hashtags=true&enable_groups=true&query=&count=10000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 334, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g0dzila/tools/osint/instagent/app/main.py", line 244, in <module>
    api_process(parms, readliner)
  File "/home/g0dzila/tools/osint/instagent/app/main.py", line 79, in api_process
    api.initialize( parms.identity, 
  File "/home/g0dzila/tools/osint/instagent/app/src/instagent.py", line 152, in initialize
    self.___setTarget___()
  File "/home/g0dzila/tools/osint/instagent/app/src/_setTarget_.py", line 26, in ___setTarget___
    self.my_following = self.api.user_following(self.api.user_id)
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 593, in user_following
    users = self.user_following_v1(user_id, amount)
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 552, in user_following_v1
    result = self.private_request(f"friendships/{user_id}/following/", params=params)
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 449, in private_request
    self.challenge_resolve(self.last_json)
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/challenge.py", line 425, in challenge_resolve_simple
    raise ChallengeUnknownStep(f'ChallengeResolve: Unknown step_name "{step_name}" for "{self.username}" in challenge resolver: {self.last_json}')
instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "select_contact_point_recovery" for "nessie.retro" in challenge resolver: {'step_name': 'select_contact_point_recovery', 'step_data': {'choice': '1', 'email': 'y*******e@hotmail.com', 'hl_co_enabled': False, 'sigp_to_hl': False}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 18195010177240725, 'challenge_context': '{"step_name": "select_contact_point_recovery", "cni": 18195010177240725, "is_stateless": false, "challenge_type_enum": "HACKED_LOCK", "present_as_modal": false}', 'challenge_type_enum_str': 'HACKED_LOCK', 'status': 'ok'}
```

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by spygency1** [comment]
> The login does not work anymore, I think it's due to somes changes by Instagram. Here is the trace:
> 
> ```
> Attempt to login...
> Traceback (most recent call last):
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 302, in _send_private_request
>     response.raise_for_status()
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/friendships/7285760724/following/?rank_token=7285760724_e8d9e19c-7be7-40a9-88da-7eec7ac40a33&search_surface=follow_list_page&includes_hashtags=true&enable_groups=true&query=&count=10000
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 438, in private_request
>     self._send_private_request(endpoint, **kwargs)
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 334, in _send_private_request
>     raise ChallengeRequired(**last_json)
> instagrapi.exceptions.ChallengeRequired: challenge_required
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/g0dzila/tools/osint/instagent/app/main.py", line 244, in <module>
>     api_process(parms, readliner)
>   File "/home/g0dzila/tools/osint/instagent/app/main.py", line 79, in api_process
>     api.initialize( parms.identity, 
>   File "/home/g0dzila/tools/osint/instagent/app/src/instagent.py", line 152, in initialize
>     self.___setTarget___()
>   File "/home/g0dzila/tools/osint/instagent/app/src/_setTarget_.py", line 26, in ___setTarget___
>     self.my_following = self.api.user_following(self.api.user_id)
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 593, in user_following
>     users = self.user_following_v1(user_id, amount)
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 552, in user_following_v1
>     result = self.private_request(f"friendships/{user_id}/following/", params=params)
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 449, in private_request
>     self.challenge_resolve(self.last_json)
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/challenge.py", line 78, in challenge_resolve
>     return self.challenge_resolve_simple(challenge_url)
>   File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/challenge.py", line 425, in challenge_resolve_simple
>     raise ChallengeUnknownStep(f'ChallengeResolve: Unknown step_name "{step_name}" for "{self.username}" in challenge resolver: {self.last_json}')
> instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "select_contact_point_recovery" for "nessie.retro" in challenge resolver: {'step_name': 'select_contact_point_recovery', 'step_data': {'choice': '1', 'email': 'y*******e@hotmail.com', 'hl_co_enabled': False, 'sigp_to_hl': False}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 18195010177240725, 'challenge_context': '{"step_name": "select_contact_point_recovery", "cni": 18195010177240725, "is_stateless": false, "challenge_type_enum": "HACKED_LOCK", "present_as_modal": false}', 'challenge_type_enum_str': 'HACKED_LOCK', 'status': 'ok'}
> ```
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1

https://instagram.com/spygency.1?igshid=MzRlODBiNWFlZA==

EMAIL 📧 spygency@gmail.com
