### ISSUE TITLE
osintgram api error

### ISSUE THREAD

**Issue by ashiahjaguar2** [t-abraham/instagent#9]
**Describe the error**
how to fix this issue on osintgram please sir reply how to solve this error many people are facing this error please sir
I have been trying to solve for a long time. But it is not happening, how have you done it?🙏🙏🙏

Attempt to login...
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
File "/home/jan/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 523, in _call_api
response = self.opener.open(req, timeout=self.timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/urllib/request.py", line 525, in open
response = meth(req, response)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
response = self.parent.error(
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/urllib/request.py", line 563, in error
return self._call_chain(*args)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
result = func(*args)
^^^^^^^^^^^
File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jan/Osintgram/main.py", line 121, in
api = Osintgram(args.id, args.file, args.json, args.command, args.output, args.cookies)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/jan/Osintgram/src/Osintgram.py", line 48, in init
self.setTarget(target)
File "/home/jan/Osintgram/src/Osintgram.py", line 61, in setTarget
self.following = self.check_following()
^^^^^^^^^^^^^^^^^^^^^^
File "/home/jan/Osintgram/src/Osintgram.py", line 1159, in check_following
return self.api._call_api(endpoint)['user_detail']['user']['friendship_status']['following']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/jan/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 527, in _call_api
ErrorHandler.process(e, error_response)
File "/home/jan/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/errors.py", line 135, in process
raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found

**Comment by ashiahjaguar2** [comment]
Sir if error is coming in your tool also then tell or fix it please sir

**Comment by ghostkernel-core** [comment]
Hi. InstAgent is independent from Osintgram and uses different API from Osintgram which is in sync with the latest securities of the Meta products. Please refrain from creating issues which are are not relevant to InstAgent.

to answer your question, no InstAgent doesn’t have this issue. Thank you.
